apiVersion: apps/v1
kind: Deployment
metadata:
  name: teiyku
spec:
  replicas: 1
  selector:
    matchLabels:
      app:teiyku
  template:
    metadata:
      labels:
        app:teiyku
    spec:
      containers:
      - image: okteto.dev/teiyku:latest
        name: teiyku
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "38b86846-a958-4fdc-bda0-8699bef4610b"
        - name: Vless_Path
          value: "/vlguhjl"
        - name: Vmess_UUID
          value: "38b86846-a958-4fdc-bda0-8699bef4610b"
        - name: Vmess_Path
          value: "/vmerux"
        - name: Share_Path
          value: "/v2link"
